---
title:
- type: main
  text: One way to Sweden
- type: subtitle
  text: L'avventura in Svezia di un meteorologo e un medico inguaribili sognatori e decisi a seguire sempre le proprie passioni
creator:
- role: author
  text: Silvia e Gabriele
- role: editor
  text: Fabio
...
